name: Package Extension Files

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: 
          - chrome
          - firefox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install zip
        
      - name: Get version number
        id: get_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package ${{ matrix.browser }} files
        run: |
          mkdir -p output_${{ matrix.browser }}
          cp manifest_${{ matrix.browser }}.json output_${{ matrix.browser }}/manifest.json
          cp -r src output_${{ matrix.browser }}/
          cp -r icons output_${{ matrix.browser }}/
          cd output_${{ matrix.browser }}
          zip -r bandcamp-stock-${{ matrix.browser }}-${{ env.VERSION }}.zip .  # Create zip package

      - name: Upload ${{ matrix.browser }} package
        uses: actions/upload-artifact@v4
        with:
          name: bandcamp-stock-${{ matrix.browser }}-${{ env.VERSION }}.zip
          path: bandcamp-stock-${{ matrix.browser }}-${{ env.VERSION }}.zip
